version: "3.7"
services:
  notebook-server:
    image: geotrellis-almond
    build: Dockerfile
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ../notebooks:/home/jovyan/workshop
      - $HOME/.aws:/home/jovyan/.aws:ro
